package main

import (
	"bytes"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
)

type htmlData struct {
	ScanDate      string
	ScanTarget    string
	TotalFindings int
	Findings      []Finding
}

var htmlTmpl = template.Must(template.New("report").Parse(rawHTML))

// writeHTMLReport writes a self-contained HTML redacted report for management review.
func writeHTMLReport(dir, suffix, scanTarget, scanDate string, findings []Finding) (string, error) {
	path := filepath.Join(dir, fmt.Sprintf("redacted-report%s.html", suffix))
	data := htmlData{
		ScanDate:      scanDate,
		ScanTarget:    scanTarget,
		TotalFindings: len(findings),
		Findings:      findings,
	}
	var buf bytes.Buffer
	if err := htmlTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return path, os.WriteFile(path, buf.Bytes(), 0644)
}

const rawHTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sensitive Data Scanner — Redacted Report</title>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;color:#1a202c;background:#f7fafc;line-height:1.5}
header{background:#1e3a5f;color:#fff;padding:1.25rem 2rem}
header h1{font-size:1.375rem;font-weight:700}
.subtitle{opacity:.75;font-size:.9rem;margin-top:.2rem}
.container{max-width:1200px;margin:0 auto;padding:1.5rem 2rem}
.meta{display:flex;flex-wrap:wrap;gap:1.5rem;background:#fff;border:1px solid #e2e8f0;border-radius:.5rem;padding:1rem 1.5rem;margin-bottom:1rem}
.meta div{display:flex;flex-direction:column;gap:.2rem}
.meta .label{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:#718096;font-weight:600}
.meta .val{font-size:.9rem;color:#2d3748;font-weight:500}
.notice{background:#fffbeb;border-left:4px solid #f6ad55;padding:.75rem 1rem;border-radius:0 .375rem .375rem 0;font-size:.85rem;color:#744210;margin-bottom:1.25rem}
table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e2e8f0;border-radius:.5rem;overflow:hidden;font-size:.85rem}
thead{background:#2d3748;color:#fff}
th{padding:.6rem 1rem;text-align:left;font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;white-space:nowrap}
td{padding:.6rem 1rem;border-bottom:1px solid #edf2f7;vertical-align:top}
tbody tr:last-child td{border-bottom:none}
tbody tr:nth-child(even){background:#f7fafc}
tbody tr:hover{background:#ebf8ff}
.num{color:#a0aec0;font-size:.8rem;text-align:right;white-space:nowrap;width:1%}
.file{font-family:'SFMono-Regular',Consolas,'Liberation Mono',Menlo,monospace;font-size:.78rem;color:#2b6cb0;word-break:break-all}
.ln{color:#718096;font-size:.8rem;text-align:right;white-space:nowrap;width:1%}
.stype{font-weight:600;color:#2d3748;white-space:nowrap}
.secret code{font-family:'SFMono-Regular',Consolas,'Liberation Mono',Menlo,monospace;background:#f0fff4;color:#276749;padding:.1rem .35rem;border-radius:.25rem;font-size:.8rem}
.empty{color:#718096;text-align:center;padding:2rem;font-style:italic}
footer{text-align:center;padding:1rem;color:#a0aec0;font-size:.75rem;border-top:1px solid #e2e8f0;margin-top:2rem}
@media print{body{background:#fff}header{-webkit-print-color-adjust:exact;print-color-adjust:exact}tbody tr:nth-child(even){background:#f7fafc!important}tbody tr:hover{background:inherit!important}}
</style>
</head>
<body>
<header>
  <h1>Sensitive Data Scanner</h1>
  <p class="subtitle">Redacted Management Report</p>
</header>
<div class="container">
  <div class="meta">
    <div><span class="label">Scan Date</span><span class="val">{{.ScanDate}}</span></div>
    <div><span class="label">Target</span><span class="val">{{.ScanTarget}}</span></div>
    <div><span class="label">Total Findings</span><span class="val">{{.TotalFindings}}</span></div>
  </div>
  <div class="notice">
    <strong>Note:</strong> Secret values are partially redacted. Full unredacted values are in the restricted full report.
  </div>
  {{if .Findings}}
  <table>
    <thead>
      <tr><th>#</th><th>File</th><th>Line</th><th>Secret Type</th><th>Redacted Value</th></tr>
    </thead>
    <tbody>
      {{range .Findings}}
      <tr>
        <td class="num">{{.ID}}</td>
        <td class="file">{{.File}}</td>
        <td class="ln">{{.LineNumber}}</td>
        <td class="stype">{{.SecretType}}</td>
        <td class="secret"><code>{{.RedactedValue}}</code></td>
      </tr>
      {{end}}
    </tbody>
  </table>
  {{else}}
  <p class="empty">No findings.</p>
  {{end}}
</div>
<footer>Generated by Sensitive Data Scanner</footer>
</body>
</html>`
